[package]
name = "croon"
version = "0.1.0"
authors = ["onatm <onatmercan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom="^4"
linked_hash_set="^0.1.4"
lazy_static = "1.4.0"
